/*
 * generated by Xtext 2.24.0
 */
package org.big.erd


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EntityRelationshipStandaloneSetup extends EntityRelationshipStandaloneSetupGenerated {

	def static void doSetup() {
		new EntityRelationshipStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
