/*
 * generated by Xtext 2.27.0
 */
package org.big.erd.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.big.erd.EntityRelationshipRuntimeModule;
import org.big.erd.EntityRelationshipStandaloneSetup;
import org.big.erd.ide.diagram.DiagramModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class EntityRelationshipIdeSetup extends EntityRelationshipStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(
					Modules2.mixin(
						new EntityRelationshipRuntimeModule(), 
						new EntityRelationshipIdeModule(),
						new DiagramModule()
				));
	}
}
