/*
 * generated by Xtext 2.27.0
 */
package org.big.erd.ide;

import org.big.erd.ide.codeActions.ERDCodeActionService;
import org.big.erd.ide.hover.ERDHoverService;
import org.big.erd.ide.symbol.ErDocumentSymbolKindProvider;
import org.big.erd.ide.symbol.ErDocumentSymbolNameProvider;
import org.eclipse.xtext.ide.server.codeActions.ICodeActionService2;
import org.eclipse.xtext.ide.server.hover.HoverService;
import org.eclipse.xtext.ide.server.symbol.DocumentSymbolMapper.DocumentSymbolKindProvider;
import org.eclipse.xtext.ide.server.symbol.DocumentSymbolMapper.DocumentSymbolNameProvider;

/**
 * Use this class to register ide components.
 */
public class EntityRelationshipIdeModule extends AbstractEntityRelationshipIdeModule {
	
	public Class<? extends ICodeActionService2> bindICodeActionService2() {
		return ERDCodeActionService.class;
	}
	
	public Class<? extends HoverService> bindHoverService() {
		return ERDHoverService.class;
	}
	
	public Class<? extends DocumentSymbolNameProvider> bindDocumentSymbolNameProvider() {
		return ErDocumentSymbolNameProvider.class;
	}
	
	public Class<? extends DocumentSymbolKindProvider> bindDocumentSymbolKindProvider() {
		return ErDocumentSymbolKindProvider.class;
	}
}
