/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.erd.ide

import org.xtext.example.erd.ide.codeActions.ERDiagramCodeActionService
import org.eclipse.xtext.ide.server.codeActions.ICodeActionService2
/**
 * Use this class to register ide components.
 */
class EntityRelationshipIdeModule extends AbstractEntityRelationshipIdeModule {
    
	
    def Class<? extends ICodeActionService2> bindICodeActionService2() {
		ERDiagramCodeActionService
	}
	
}
