/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.erd


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class EntityRelationshipRuntimeModule extends AbstractEntityRelationshipRuntimeModule {
}
